[font]
size = 13

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
#family = "JetBrainsMono Nerd Font Mono"
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
padding = { x = 15, y = 15 }

[general]
import = [
    "./themes/themes/oceanic_next.toml"
]

